// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ChannelLogPayload { event_type: string, guild_id: string, category_id: string, channel_id: string, channel_name: string, message_id: string, message_timestamp: string, member_id: string, data: string, }