// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIResponseError } from "./APIResponseError";

export interface APIResponse<T> { success: boolean, response: T | null, errors: Array<APIResponseError>, requested_at: bigint, completed_at: bigint, }