// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PaginationData { total_results: number, total_pages: number, page: number, limit: number, showing: number, term: string, }