use std::fmt::{self, Formatter};

#[derive(Eq, Hash, PartialEq, Clone)]
pub enum DestinyComponentType {
    None,
    /// Profiles is the most basic component, only relevant when calling GetProfile.
    /// This returns basic information about the profile, which is almost nothing: a list of characterIds,
    /// some information about the last time you logged in, and that most sobering statistic: how long you've played.
    Profiles,

    /// Only applicable for GetProfile, this will return information about receipts for refundable vendor items.
    VendorReceipts,

    /// Asking for this will get you the profile-level inventories, such as your Vault buckets (yeah, the Vault is really inventory buckets located on your Profile)
    ProfileInventories,

    /// This will get you a summary of items on your Profile that we consider to be "currencies", such as Glimmer. I mean, if there's Glimmer in Destiny 2. I didn't say there was Glimmer.
    ProfileCurrencies,

    /// This will get you any progression-related information that exists on a Profile-wide level, across all characters.
    ProfileProgression,

    /// This will get you information about the silver that this profile has on every platform on which it plays.
    ///  You may only request this component for the logged in user's Profile, and will not receive it if you request it for another Profile.
    ProfileSilver,

    /// This will get you summary info about each of the characters in the profile.
    Characters,

    /// This will get you information about any non-equipped items on the character or character(s) in question, if you're allowed to see it. You have to either be authenticated as that user,
    /// or that user must allow anonymous viewing of their non-equipped items in Bungie.Net settings to actually get results.
    CharacterInventories,

    /// This will get you information about the progression (faction, experience, etc... "levels") relevant to each character,
    /// if you are the currently authenticated user or the user has elected to allow anonymous viewing of its progression info.
    CharacterProgressions,

    /// This will get you just enough information to be able to render the character in 3D if you have written a 3D rendering library for Destiny Characters, or "borrowed" ours. It's okay, I won't tell anyone if you're using it. I'm no snitch. (actually, we don't care if you use it - go to town)
    CharacterRenderData,

    /// This will return info about activities that a user can see and gating on it,
    /// if you are the currently authenticated user or the user has elected to allow anonymous viewing of its progression info.
    /// Note that the data returned by this can be unfortunately problematic and relatively unreliable in some cases. We'll eventually work on making it more consistently reliable.
    CharacterActivities,

    /// This will return info about the equipped items on the character(s). Everyone can see this.
    CharacterEquipment,

    /// This will return info about the loadouts of the character(s).
    CharacterLoadouts,

    /// This will return basic info about instanced items - whether they can be equipped, their tracked status, and some info commonly needed in many places (current damage type, primary stat value, etc)
    ItemInstances,

    /// Items can have Objectives (DestinyObjectiveDefinition) bound to them. If they do, this will return info for items that have such bound objectives.
    ItemObjectives,

    /// Items can have perks (DestinyPerkDefinition). If they do, this will return info for what perks are active on items.
    ItemPerks,

    /// If you just want to render the weapon, this is just enough info to do that rendering.
    ItemRenderData,

    /// Items can have stats, like rate of fire. Asking for this component will return requested item's stats if they have stats.
    ItemStats,

    /// Items can have sockets, where plugs can be inserted. Asking for this component will return all info relevant to the sockets on items that have them.
    ItemSockets,

    /// Items can have talent grids, though that matters a lot less frequently than it used to. Asking for this component will return all relevant info about activated Nodes and
    /// Steps on this talent grid, like the good ol' days.
    ItemTalentGrids,

    /// Items that *aren't* instanced still have important information you need to know: how much of it you have,
    /// the itemHash so you can look up their DestinyInventoryItemDefinition, whether they're locked, etc...
    /// Both instanced and non-instanced items will have these properties. You will get this automatically with Inventory components - you only need to pass this when calling GetItem on a specific item.
    ItemCommonData,

    /// Items that are "Plugs" can be inserted into sockets. This returns statuses about those plugs and why they can/can't be inserted.
    /// I hear you giggling, there's nothing funny about inserting plugs. Get your head out of the gutter and pay attention!
    ItemPlugStates,

    /// Sometimes, plugs have objectives on them. This data can get really large, so we split it into its own component. Please, don't grab it unless you need it.
    ItemPlugObjectives,

    /// Sometimes, designers create thousands of reusable plugs and suddenly your response sizes are almost 3MB, and something has to give.
    ///
    /// Reusable Plugs were split off as their own component, away from ItemSockets, as a result of the Plug changes in Shadowkeep that made plug data infeasibly large for the most common use cases.
    ///
    /// Request this component if and only if you need to know what plugs *could* be inserted into a socket, and need to know it before "drilling" into the details of an item in your application (for instance, if you're doing some sort of interesting sorting or aggregation based on available plugs.
    ///
    /// When you get this, you will also need to combine it with "Plug Sets" data if you want a full picture of all of the available plugs: this component will only return plugs that have state data that is per-item. See Plug Sets for available plugs that have Character, Profile, or no state-specific restrictions.
    ItemReusablePlugs,

    /// When obtaining vendor information, this will return summary information about the Vendor or Vendors being returned.
    Vendor,

    /// When obtaining vendor information, this will return information about the categories of items provided by the Vendor.
    VendorCategories,

    /// When obtaining vendor information, this will return the information about items being sold by the Vendor.
    VendorSales,

    /// Asking for this component will return you the account's Kiosk statuses: that is, what items have been filled out/acquired.
    /// But only if you are the currently authenticated user or the user has elected to allow anonymous viewing of its progression info.
    Kiosks,

    /// A "shortcut" component that will give you all of the item hashes/quantities of items that the requested character can use to determine if an action (purchasing, socket insertion)
    /// has the required currency. (recall that all currencies are just items, and that some vendor purchases require items that you might not traditionally consider to be a "currency", like plugs/mods!)
    CurrencyLookups,

    /// Returns summary status information about all "Presentation Nodes". See DestinyPresentationNodeDefinition for more details, but the gist is that these are entities used by the game UI to bucket Collectibles and Records into a hierarchy of categories.
    /// You may ask for and use this data if you want to perform similar bucketing in your own UI: or you can skip it and roll your own.
    PresentationNodes,

    /// Returns summary status information about all "Collectibles". These are records of what items you've discovered while playing Destiny, and some other basic information.
    /// For detailed information, you will have to call a separate endpoint devoted to the purpose.
    Collectibles,

    /// Returns summary status information about all "Records" (also known in the game as "Triumphs". I know, it's confusing because there's also "Moments of Triumph" that will themselves be represented as "Triumphs.")
    Records,

    /// Returns information that Bungie considers to be "Transitory": data that may change too frequently or come from a non-authoritative
    /// source such that we don't consider the data to be fully trustworthy, but that might prove useful for some limited use cases.
    /// We can provide no guarantee of timeliness nor consistency for this data: buyer beware with the Transitory component.
    Transitory,

    /// Returns summary status information about all "Metrics" (also known in the game as "Stat Trackers").
    Metrics,

    /// Returns a mapping of localized string variable hashes to values, on a per-account or per-character basis.
    StringVariables,

    /// Returns summary status information about all "Craftables" aka crafting recipe items.
    Craftables,

    /// Returns score values for all commendations and commendation nodes.
    SocialCommendations,
}

impl From<DestinyComponentType> for &'static str {
    fn from(component_type: DestinyComponentType) -> Self {
        match component_type {
            DestinyComponentType::None => "",
            DestinyComponentType::Profiles => "Profiles",
            DestinyComponentType::VendorReceipts => "VendorReceipts",
            DestinyComponentType::ProfileInventories => "ProfileInventories",
            DestinyComponentType::ProfileCurrencies => "ProfileCurrencies",
            DestinyComponentType::ProfileProgression => "ProfileProgression",
            DestinyComponentType::ProfileSilver => "ProfileSilver",
            DestinyComponentType::Characters => "Characters",
            DestinyComponentType::CharacterInventories => "CharacterInventories",
            DestinyComponentType::CharacterProgressions => "CharacterProgressions",
            DestinyComponentType::CharacterRenderData => "CharacterRenderData",
            DestinyComponentType::CharacterActivities => "CharacterActivities",
            DestinyComponentType::CharacterEquipment => "CharacterEquipment",
            DestinyComponentType::CharacterLoadouts => "CharacterLoadouts",
            DestinyComponentType::ItemInstances => "ItemInstances",
            DestinyComponentType::ItemObjectives => "ItemObjectives",
            DestinyComponentType::ItemPerks => "ItemPerks",
            DestinyComponentType::ItemRenderData => "ItemRenderData",
            DestinyComponentType::ItemStats => "ItemStats",
            DestinyComponentType::ItemSockets => "ItemSockets",
            DestinyComponentType::ItemTalentGrids => "ItemTalentGrids",
            DestinyComponentType::ItemCommonData => "ItemCommonData",
            DestinyComponentType::ItemPlugStates => "ItemPlugStates",
            DestinyComponentType::ItemPlugObjectives => "ItemPlugObjectives",
            DestinyComponentType::ItemReusablePlugs => "ItemReusablePlugs",
            DestinyComponentType::Vendor => "Vendor",
            DestinyComponentType::VendorCategories => "VendorCategories",
            DestinyComponentType::VendorSales => "VendorSales",
            DestinyComponentType::Kiosks => "Kiosks",
            DestinyComponentType::CurrencyLookups => "CurrencyLookups",
            DestinyComponentType::PresentationNodes => "PresentationNodes",
            DestinyComponentType::Collectibles => "Collectibles",
            DestinyComponentType::Records => "Records",
            DestinyComponentType::Transitory => "Transitory",
            DestinyComponentType::Metrics => "Metrics",
            DestinyComponentType::StringVariables => "StringVariables",
            DestinyComponentType::Craftables => "Craftables",
            DestinyComponentType::SocialCommendations => "SocialCommendations",
        }
    }
}

impl From<&DestinyComponentType> for &'static str {
    fn from(value: &DestinyComponentType) -> Self {
        value.clone().into()
    }
}

impl DestinyComponentType {
    pub fn as_str(&self) -> &str {
        self.clone().into()
    }
}

#[derive(Eq, Hash, PartialEq, Clone)]
pub enum DestinyRouteParam {
    /// {id}
    BungieNetMembershipID,
    /// {membershipId}
    PlatformMembershipID,
    /// {membershipType}
    PlatformMembershipType,
    /// {mType}
    MType,
    /// {crType}
    CredentialType,
    /// {credential}
    Credential,
    /// {page}
    Page,
    /// {type}
    ContentType,
    /// {locale}
    Locale,
    /// {searchtext}
    SearchText,
    /// {tag}
    Tag,
    /// {size}
    Size,
    /// {pageToken}
    PageToken,
    /// {pageSize}
    PageSize,
    /// {group}
    Group,
    /// {sort}
    Sort,
    /// {quickDate}
    QuickDate,
    /// {categoryFilter}
    CategoryFilter,
    /// {replySize}
    ReplySize,
    /// {getParentPost}
    GetParentPost,
    /// {rootThreadMode}
    RootThreadMode,
    /// {sortMode}
    SortMode,
    /// {childPostId}
    ChildPostID,
    /// {contentID}
    ContentID,
    /// {topicId}
    TopicID,
    /// {createDateRange}
    CreateDateRange,
    /// {conversationId}
    ConversationId,
    /// {memberType}
    MemberType,
    /// {founderIdNew}
    FounderIDNew,
    /// {filter}
    Filter,
    /// {groupType}
    GroupType,

    /// {groupId}
    GroupID,

    /// {characterId}
    Character,

    /// {activityId}
    Activity,
}

impl From<DestinyRouteParam> for &'static str {
    fn from(value: DestinyRouteParam) -> Self {
        match value {
            DestinyRouteParam::BungieNetMembershipID => "{id}",
            DestinyRouteParam::PlatformMembershipID => "{membershipId}",
            DestinyRouteParam::PlatformMembershipType => "{membershipType}",
            DestinyRouteParam::MType => "{mType}",
            DestinyRouteParam::CredentialType => "{crType}",
            DestinyRouteParam::Credential => "{credential}",
            DestinyRouteParam::Page => "{page}",
            DestinyRouteParam::ContentType => "{type}",
            DestinyRouteParam::Locale => "{locale}",
            DestinyRouteParam::SearchText => "{searchtext}",
            DestinyRouteParam::Tag => "{tag}",
            DestinyRouteParam::Size => "{size}",
            DestinyRouteParam::PageToken => "{pageToken}",
            DestinyRouteParam::PageSize => "{pageSize}",
            DestinyRouteParam::Group => "{group}",
            DestinyRouteParam::Sort => "{sort}",
            DestinyRouteParam::QuickDate => "{quickDate}",
            DestinyRouteParam::CategoryFilter => "{categoryFilter}",
            DestinyRouteParam::ReplySize => "{replySize}",
            DestinyRouteParam::GetParentPost => "{getParentPost}",
            DestinyRouteParam::RootThreadMode => "{rootThreadMode}",
            DestinyRouteParam::SortMode => "{sortMode}",
            DestinyRouteParam::ChildPostID => "{childPostId}",
            DestinyRouteParam::ContentID => "{contentID}",
            DestinyRouteParam::TopicID => "{topicID}",
            DestinyRouteParam::CreateDateRange => "{createDateRange}",
            DestinyRouteParam::ConversationId => "{conversationId}",
            DestinyRouteParam::MemberType => "{memberType}",
            DestinyRouteParam::FounderIDNew => "{founderIdNew}",
            DestinyRouteParam::Filter => "{filter}",
            DestinyRouteParam::GroupType => "{groupType}",
            DestinyRouteParam::GroupID => "{groupId}",
            DestinyRouteParam::Character => "{characterId}",
            DestinyRouteParam::Activity => "{activityId}",
        }
    }
}

impl From<&DestinyRouteParam> for &'static str {
    fn from(value: &DestinyRouteParam) -> Self {
        value.clone().into()
    }
}

impl DestinyRouteParam {
    pub fn as_str(&self) -> &str {
        self.clone().into()
    }
}

/// https://bungie-net.github.io/#/components/schemas/Exceptions.PlatformErrorCodes
#[derive(PartialEq, Eq)]
#[repr(i32)]
#[allow(dead_code)]
pub enum PlatformErrorCodes {
    None = 0,
    Success = 1,
    TransportException = 2,
    UnhandledException = 3,
    NotImplemented = 4,
    SystemDisabled = 5,
    FailedToLoadAvailableLocalesConfiguration = 6,
    ParameterParseFailure = 7,
    ParameterInvalidRange = 8,
    BadRequest = 9,
    AuthenticationInvalid = 10,
    DataNotFound = 11,
    InsufficientPrivileges = 12,
    Duplicate = 13,
    UnknownSqlResult = 14,
    ValidationError = 15,
    ValidationMissingFieldError = 16,
    ValidationInvalidInputError = 17,
    InvalidParameters = 18,
    ParameterNotFound = 19,
    UnhandledHttpException = 20,
    NotFound = 21,
    WebAuthModuleAsyncFailed = 22,
    InvalidReturnValue = 23,
    UserBanned = 24,
    InvalidPostBody = 25,
    MissingPostBody = 26,
    ExternalServiceTimeout = 27,
    ValidationLengthError = 28,
    ValidationRangeError = 29,
    JsonDeserializationError = 30,
    ThrottleLimitExceeded = 31,
    ValidationTagError = 32,
    ValidationProfanityError = 33,
    ValidationUrlFormatError = 34,
    ThrottleLimitExceededMinutes = 35,
    ThrottleLimitExceededMomentarily = 36,
    ThrottleLimitExceededSeconds = 37,
    ExternalServiceUnknown = 38,
    ValidationWordLengthError = 39,
    ValidationInvisibleUnicode = 40,
    ValidationBadNames = 41,
    ExternalServiceFailed = 42,
    ServiceRetired = 43,
    UnknownSqlException = 44,
    UnsupportedLocale = 45,
    InvalidPageNumber = 46,
    MaximumPageSizeExceeded = 47,
    ServiceUnsupported = 48,
    ValidationMaximumUnicodeCombiningCharacters = 49,
    ValidationMaximumSequentialCarriageReturns = 50,
    PerEndpointRequestThrottleExceeded = 51,
    AuthContextCacheAssertion = 52,
    ExPlatformStringValidationError = 53,
    PerApplicationThrottleExceeded = 54,
    PerApplicationAnonymousThrottleExceeded = 55,
    PerApplicationAuthenticatedThrottleExceeded = 56,
    PerUserThrottleExceeded = 57,
    PayloadSignatureVerificationFailure = 58,
    InvalidServiceAuthContext = 59,
    ObsoleteCredentialType = 89,
    UnableToUnPairMobileApp = 90,
    UnableToPairMobileApp = 91,
    CannotUseMobileAuthWithNonMobileProvider = 92,
    MissingDeviceCookie = 93,
    FacebookTokenExpired = 94,
    AuthTicketRequired = 95,
    CookieContextRequired = 96,
    UnknownAuthenticationError = 97,
    BungieNetAccountCreationRequired = 98,
    WebAuthRequired = 99,
    ContentUnknownSqlResult = 100,
    ContentNeedUniquePath = 101,
    ContentSqlException = 102,
    ContentNotFound = 103,
    ContentSuccessWithTagAddFail = 104,
    ContentSearchMissingParameters = 105,
    ContentInvalidId = 106,
    ContentPhysicalFileDeletionError = 107,
    ContentPhysicalFileCreationError = 108,
    ContentPerforceSubmissionError = 109,
    ContentPerforceInitializationError = 110,
    ContentDeploymentPackageNotReadyError = 111,
    ContentUploadFailed = 112,
    ContentTooManyResults = 113,
    ContentInvalidState = 115,
    ContentNavigationParentNotFound = 116,
    ContentNavigationParentUpdateError = 117,
    DeploymentPackageNotEditable = 118,
    ContentValidationError = 119,
    ContentPropertiesValidationError = 120,
    ContentTypeNotFound = 121,
    DeploymentPackageNotFound = 122,
    ContentSearchInvalidParameters = 123,
    ContentItemPropertyAggregationError = 124,
    DeploymentPackageFileNotFound = 125,
    ContentPerforceFileHistoryNotFound = 126,
    ContentAssetZipCreationFailure = 127,
    ContentAssetZipCreationBusy = 128,
    ContentProjectNotFound = 129,
    ContentFolderNotFound = 130,
    ContentPackagesInconsistent = 131,
    ContentPackagesInvalidState = 132,
    ContentPackagesInconsistentType = 133,
    ContentCannotDeletePackage = 134,
    ContentLockedForChanges = 135,
    ContentFileUploadFailed = 136,
    ContentNotReviewed = 137,
    ContentPermissionDenied = 138,
    ContentInvalidExternalUrl = 139,
    ContentExternalFileCannotBeImportedLocally = 140,
    ContentTagSaveFailure = 141,
    ContentPerforceUnmatchedFileError = 142,
    ContentPerforceChangelistResultNotFound = 143,
    ContentPerforceChangelistFileItemsNotFound = 144,
    ContentPerforceInvalidRevisionError = 145,
    ContentUnloadedSaveResult = 146,
    ContentPropertyInvalidNumber = 147,
    ContentPropertyInvalidUrl = 148,
    ContentPropertyInvalidDate = 149,
    ContentPropertyInvalidSet = 150,
    ContentPropertyCannotDeserialize = 151,
    ContentRegexValidationFailOnProperty = 152,
    ContentMaxLengthFailOnProperty = 153,
    ContentPropertyUnexpectedDeserializationError = 154,
    ContentPropertyRequired = 155,
    ContentCannotCreateFile = 156,
    ContentInvalidMigrationFile = 157,
    ContentMigrationAlteringProcessedItem = 158,
    ContentPropertyDefinitionNotFound = 159,
    ContentReviewDataChanged = 160,
    ContentRollbackRevisionNotInPackage = 161,
    ContentItemNotBasedOnLatestRevision = 162,
    ContentUnauthorized = 163,
    ContentCannotCreateDeploymentPackage = 164,
    ContentUserNotFound = 165,
    ContentLocalePermissionDenied = 166,
    ContentInvalidLinkToInternalEnvironment = 167,
    ContentInvalidBlacklistedContent = 168,
    ContentMacroMalformedNoContentId = 169,
    ContentMacroMalformedNoTemplateType = 170,
    ContentIllegalBNetMembershipId = 171,
    ContentLocaleDidNotMatchExpected = 172,
    ContentBabelCallFailed = 173,
    ContentEnglishPostLiveForbidden = 174,
    ContentLocaleEditPermissionDenied = 175,
    ContentStackUnknownError = 176,
    ContentStackNotFound = 177,
    ContentStackRateLimited = 178,
    ContentStackTimeout = 179,
    ContentStackServiceError = 180,
    ContentStackDeserializationFailure = 181,
    UserNonUniqueName = 200,
    UserManualLinkingStepRequired = 201,
    UserCreateUnknownSqlResult = 202,
    UserCreateUnknownSqlException = 203,
    UserMalformedMembershipId = 204,
    UserCannotFindRequestedUser = 205,
    UserCannotLoadAccountCredentialLinkInfo = 206,
    UserInvalidMobileAppType = 207,
    UserMissingMobilePairingInfo = 208,
    UserCannotGenerateMobileKeyWhileUsingMobileCredential = 209,
    UserGenerateMobileKeyExistingSlotCollision = 210,
    UserDisplayNameMissingOrInvalid = 211,
    UserCannotLoadAccountProfileData = 212,
    UserCannotSaveUserProfileData = 213,
    UserEmailMissingOrInvalid = 214,
    UserTermsOfUseRequired = 215,
    UserCannotCreateNewAccountWhileLoggedIn = 216,
    UserCannotResolveCentralAccount = 217,
    UserInvalidAvatar = 218,
    UserMissingCreatedUserResult = 219,
    UserCannotChangeUniqueNameYet = 220,
    UserCannotChangeDisplayNameYet = 221,
    UserCannotChangeEmail = 222,
    UserUniqueNameMustStartWithLetter = 223,
    UserNoLinkedAccountsSupportFriendListings = 224,
    UserAcknowledgmentTableFull = 225,
    UserCreationDestinyMembershipRequired = 226,
    UserFriendsTokenNeedsRefresh = 227,
    UserEmailValidationUnknown = 228,
    UserEmailValidationLimit = 229,
    TransactionEmailSendFailure = 230,
    MailHookPermissionFailure = 231,
    MailServiceRateLimit = 232,
    UserEmailMustBeVerified = 233,
    UserMustAllowCustomerServiceEmails = 234,
    NonTransactionalEmailSendFailure = 235,
    UnknownErrorSettingGlobalDisplayName = 236,
    DuplicateGlobalDisplayName = 237,
    ErrorRunningNameValidationChecks = 238,
    ErrorDatabaseGlobalName = 239,
    ErrorNoAvailableNameChanges = 240,
    ErrorNameAlreadySetToInput = 241,
    UserDisplayNameLessThanMinLength = 242,
    UserDisplayNameGreaterThanMaxLength = 243,
    UserDisplayNameContainsUnacceptableOrInvalidContent = 244,
    MessagingUnknownError = 300,
    MessagingSelfError = 301,
    MessagingSendThrottle = 302,
    MessagingNoBody = 303,
    MessagingTooManyUsers = 304,
    MessagingCanNotLeaveConversation = 305,
    MessagingUnableToSend = 306,
    MessagingDeletedUserForbidden = 307,
    MessagingCannotDeleteExternalConversation = 308,
    MessagingGroupChatDisabled = 309,
    MessagingMustIncludeSelfInPrivateMessage = 310,
    MessagingSenderIsBanned = 311,
    MessagingGroupOptionalChatExceededMaximum = 312,
    PrivateMessagingRequiresDestinyMembership = 313,
    AddSurveyAnswersUnknownSqlException = 400,
    ForumBodyCannotBeEmpty = 500,
    ForumSubjectCannotBeEmptyOnTopicPost = 501,
    ForumCannotLocateParentPost = 502,
    ForumThreadLockedForReplies = 503,
    ForumUnknownSqlResultDuringCreatePost = 504,
    ForumUnknownTagCreationError = 505,
    ForumUnknownSqlResultDuringTagItem = 506,
    ForumUnknownExceptionCreatePost = 507,
    ForumQuestionMustBeTopicPost = 508,
    ForumExceptionDuringTagSearch = 509,
    ForumExceptionDuringTopicRetrieval = 510,
    ForumAliasedTagError = 511,
    ForumCannotLocateThread = 512,
    ForumUnknownExceptionEditPost = 513,
    ForumCannotLocatePost = 514,
    ForumUnknownExceptionGetOrCreateTags = 515,
    ForumEditPermissionDenied = 516,
    ForumUnknownSqlResultDuringTagIdRetrieval = 517,
    ForumCannotGetRating = 518,
    ForumUnknownExceptionGetRating = 519,
    ForumRatingsAccessError = 520,
    ForumRelatedPostAccessError = 521,
    ForumLatestReplyAccessError = 522,
    ForumUserStatusAccessError = 523,
    ForumAuthorAccessError = 524,
    ForumGroupAccessError = 525,
    ForumUrlExpectedButMissing = 526,
    ForumRepliesCannotBeEmpty = 527,
    ForumRepliesCannotBeInDifferentGroups = 528,
    ForumSubTopicCannotBeCreatedAtThisThreadLevel = 529,
    ForumCannotCreateContentTopic = 530,
    ForumTopicDoesNotExist = 531,
    ForumContentCommentsNotAllowed = 532,
    ForumUnknownSqlResultDuringEditPost = 533,
    ForumUnknownSqlResultDuringGetPost = 534,
    ForumPostValidationBadUrl = 535,
    ForumBodyTooLong = 536,
    ForumSubjectTooLong = 537,
    ForumAnnouncementNotAllowed = 538,
    ForumCannotShareOwnPost = 539,
    ForumEditNoOp = 540,
    ForumUnknownDatabaseErrorDuringGetPost = 541,
    ForumExceeedMaximumRowLimit = 542,
    ForumCannotSharePrivatePost = 543,
    ForumCannotCrossPostBetweenGroups = 544,
    ForumIncompatibleCategories = 555,
    ForumCannotUseTheseCategoriesOnNonTopicPost = 556,
    ForumCanOnlyDeleteTopics = 557,
    ForumDeleteSqlException = 558,
    ForumDeleteSqlUnknownResult = 559,
    ForumTooManyTags = 560,
    ForumCanOnlyRateTopics = 561,
    ForumBannedPostsCannotBeEdited = 562,
    ForumThreadRootIsBanned = 563,
    ForumCannotUseOfficialTagCategoryAsTag = 564,
    ForumAnswerCannotBeMadeOnCreatePost = 565,
    ForumAnswerCannotBeMadeOnEditPost = 566,
    ForumAnswerPostIdIsNotADirectReplyOfQuestion = 567,
    ForumAnswerTopicIdIsNotAQuestion = 568,
    ForumUnknownExceptionDuringMarkAnswer = 569,
    ForumUnknownSqlResultDuringMarkAnswer = 570,
    ForumCannotRateYourOwnPosts = 571,
    ForumPollsMustBeTheFirstPostInTopic = 572,
    ForumInvalidPollInput = 573,
    ForumGroupAdminEditNonMember = 574,
    ForumCannotEditModeratorEditedPost = 575,
    ForumRequiresDestinyMembership = 576,
    ForumUnexpectedError = 577,
    ForumAgeLock = 578,
    ForumMaxPages = 579,
    ForumMaxPagesOldestFirst = 580,
    ForumCannotApplyForumIdWithoutTags = 581,
    ForumCannotApplyForumIdToNonTopics = 582,
    ForumCannotDownvoteCommunityCreations = 583,
    ForumTopicsMustHaveOfficialCategory = 584,
    ForumRecruitmentTopicMalformed = 585,
    ForumRecruitmentTopicNotFound = 586,
    ForumRecruitmentTopicNoSlotsRemaining = 587,
    ForumRecruitmentTopicKickBan = 588,
    ForumRecruitmentTopicRequirementsNotMet = 589,
    ForumRecruitmentTopicNoPlayers = 590,
    ForumRecruitmentApproveFailMessageBan = 591,
    ForumRecruitmentGlobalBan = 592,
    ForumUserBannedFromThisTopic = 593,
    ForumRecruitmentFireteamMembersOnly = 594,
    ForumRequiresDestiny2Progress = 595,
    ForumRequiresDestiny2EntitlementPurchase = 596,
    GroupMembershipApplicationAlreadyResolved = 601,
    GroupMembershipAlreadyApplied = 602,
    GroupMembershipInsufficientPrivileges = 603,
    GroupIdNotReturnedFromCreation = 604,
    GroupSearchInvalidParameters = 605,
    GroupMembershipPendingApplicationNotFound = 606,
    GroupInvalidId = 607,
    GroupInvalidMembershipId = 608,
    GroupInvalidMembershipType = 609,
    GroupMissingTags = 610,
    GroupMembershipNotFound = 611,
    GroupInvalidRating = 612,
    GroupUserFollowingAccessError = 613,
    GroupUserMembershipAccessError = 614,
    GroupCreatorAccessError = 615,
    GroupAdminAccessError = 616,
    GroupPrivatePostNotViewable = 617,
    GroupMembershipNotLoggedIn = 618,
    GroupNotDeleted = 619,
    GroupUnknownErrorUndeletingGroup = 620,
    GroupDeleted = 621,
    GroupNotFound = 622,
    GroupMemberBanned = 623,
    GroupMembershipClosed = 624,
    GroupPrivatePostOverrideError = 625,
    GroupNameTaken = 626,
    GroupDeletionGracePeriodExpired = 627,
    GroupCannotCheckBanStatus = 628,
    GroupMaximumMembershipCountReached = 629,
    NoDestinyAccountForClanPlatform = 630,
    AlreadyRequestingMembershipForClanPlatform = 631,
    AlreadyClanMemberOnPlatform = 632,
    GroupJoinedCannotSetClanName = 633,
    GroupLeftCannotClearClanName = 634,
    GroupRelationshipRequestPending = 635,
    GroupRelationshipRequestBlocked = 636,
    GroupRelationshipRequestNotFound = 637,
    GroupRelationshipBlockNotFound = 638,
    GroupRelationshipNotFound = 639,
    GroupAlreadyAllied = 641,
    GroupAlreadyMember = 642,
    GroupRelationshipAlreadyExists = 643,
    InvalidGroupTypesForRelationshipRequest = 644,
    GroupAtMaximumAlliances = 646,
    GroupCannotSetClanOnlySettings = 647,
    ClanCannotSetTwoDefaultPostTypes = 648,
    GroupMemberInvalidMemberType = 649,
    GroupInvalidPlatformType = 650,
    GroupMemberInvalidSort = 651,
    GroupInvalidResolveState = 652,
    ClanAlreadyEnabledForPlatform = 653,
    ClanNotEnabledForPlatform = 654,
    ClanEnabledButCouldNotJoinNoAccount = 655,
    ClanEnabledButCouldNotJoinAlreadyMember = 656,
    ClanCannotJoinNoCredential = 657,
    NoClanMembershipForPlatform = 658,
    GroupToGroupFollowLimitReached = 659,
    ChildGroupAlreadyInAlliance = 660,
    OwnerGroupAlreadyInAlliance = 661,
    AllianceOwnerCannotJoinAlliance = 662,
    GroupNotInAlliance = 663,
    ChildGroupCannotInviteToAlliance = 664,
    GroupToGroupAlreadyFollowed = 665,
    GroupToGroupNotFollowing = 666,
    ClanMaximumMembershipReached = 667,
    ClanNameNotValid = 668,
    ClanNameNotValidError = 669,
    AllianceOwnerNotDefined = 670,
    AllianceChildNotDefined = 671,
    ClanCultureIllegalCharacters = 672,
    ClanTagIllegalCharacters = 673,
    ClanRequiresInvitation = 674,
    ClanMembershipClosed = 675,
    ClanInviteAlreadyMember = 676,
    GroupInviteAlreadyMember = 677,
    GroupJoinApprovalRequired = 678,
    ClanTagRequired = 679,
    GroupNameCannotStartOrEndWithWhiteSpace = 680,
    ClanCallsignCannotStartOrEndWithWhiteSpace = 681,
    ClanMigrationFailed = 682,
    ClanNotEnabledAlreadyMemberOfAnotherClan = 683,
    GroupModerationNotPermittedOnNonMembers = 684,
    ClanCreationInWorldServerFailed = 685,
    ClanNotFound = 686,
    ClanMembershipLevelDoesNotPermitThatAction = 687,
    ClanMemberNotFound = 688,
    ClanMissingMembershipApprovers = 689,
    ClanInWrongStateForRequestedAction = 690,
    ClanNameAlreadyUsed = 691,
    ClanTooFewMembers = 692,
    ClanInfoCannotBeWhitespace = 693,
    GroupCultureThrottle = 694,
    ClanTargetDisallowsInvites = 695,
    ClanInvalidOperation = 696,
    ClanFounderCannotLeaveWithoutAbdication = 697,
    ClanNameReserved = 698,
    ClanApplicantInClanSoNowInvited = 699,
    ActivitiesUnknownException = 701,
    ActivitiesParameterNull = 702,
    ActivityCountsDiabled = 703,
    ActivitySearchInvalidParameters = 704,
    ActivityPermissionDenied = 705,
    ShareAlreadyShared = 706,
    ActivityLoggingDisabled = 707,
    ClanRequiresExistingDestinyAccount = 750,
    ClanNameRestricted = 751,
    ClanCreationBan = 752,
    ClanCreationTenureRequirementsNotMet = 753,
    ClanFieldContainsReservedTerms = 754,
    ClanFieldContainsInappropriateContent = 755,
    ItemAlreadyFollowed = 801,
    ItemNotFollowed = 802,
    CannotFollowSelf = 803,
    GroupFollowLimitExceeded = 804,
    TagFollowLimitExceeded = 805,
    UserFollowLimitExceeded = 806,
    FollowUnsupportedEntityType = 807,
    NoValidTagsInList = 900,
    BelowMinimumSuggestionLength = 901,
    CannotGetSuggestionsOnMultipleTagsSimultaneously = 902,
    NotAValidPartialTag = 903,
    TagSuggestionsUnknownSqlResult = 904,
    TagsUnableToLoadPopularTagsFromDatabase = 905,
    TagInvalid = 906,
    TagNotFound = 907,
    SingleTagExpected = 908,
    TagsExceededMaximumPerItem = 909,
    IgnoreInvalidParameters = 1000,
    IgnoreSqlException = 1001,
    IgnoreErrorRetrievingGroupPermissions = 1002,
    IgnoreErrorInsufficientPermission = 1003,
    IgnoreErrorRetrievingItem = 1004,
    IgnoreCannotIgnoreSelf = 1005,
    IgnoreIllegalType = 1006,
    IgnoreNotFound = 1007,
    IgnoreUserGloballyIgnored = 1008,
    IgnoreUserIgnored = 1009,
    TargetUserIgnored = 1010,
    NotificationSettingInvalid = 1100,
    PsnApiExpiredAccessToken = 1204,
    PSNExForbidden = 1205,
    PSNExSystemDisabled = 1218,
    PsnApiErrorCodeUnknown = 1223,
    PsnApiErrorWebException = 1224,
    PsnApiBadRequest = 1225,
    PsnApiAccessTokenRequired = 1226,
    PsnApiInvalidAccessToken = 1227,
    PsnApiBannedUser = 1229,
    PsnApiAccountUpgradeRequired = 1230,
    PsnApiServiceTemporarilyUnavailable = 1231,
    PsnApiServerBusy = 1232,
    PsnApiUnderMaintenance = 1233,
    PsnApiProfileUserNotFound = 1234,
    PsnApiProfilePrivacyRestriction = 1235,
    PsnApiProfileUnderMaintenance = 1236,
    PsnApiAccountAttributeMissing = 1237,
    PsnApiNoPermission = 1238,
    PsnApiTargetUserBlocked = 1239,
    PsnApiJwksMissing = 1240,
    PsnApiJwtMalformedHeader = 1241,
    PsnApiJwtMalformedPayload = 1242,
    XblExSystemDisabled = 1300,
    XblExUnknownError = 1301,
    XblApiErrorWebException = 1302,
    XblStsTokenInvalid = 1303,
    XblStsMissingToken = 1304,
    XblStsExpiredToken = 1305,
    XblAccessToTheSandboxDenied = 1306,
    XblMsaResponseMissing = 1307,
    XblMsaAccessTokenExpired = 1308,
    XblMsaInvalidRequest = 1309,
    XblMsaFriendsRequireSignIn = 1310,
    XblUserActionRequired = 1311,
    XblParentalControls = 1312,
    XblDeveloperAccount = 1313,
    XblUserTokenExpired = 1314,
    XblUserTokenInvalid = 1315,
    XblOffline = 1316,
    XblUnknownErrorCode = 1317,
    XblMsaInvalidGrant = 1318,
    ReportNotYetResolved = 1400,
    ReportOverturnDoesNotChangeDecision = 1401,
    ReportNotFound = 1402,
    ReportAlreadyReported = 1403,
    ReportInvalidResolution = 1404,
    ReportNotAssignedToYou = 1405,
    LegacyGameStatsSystemDisabled = 1500,
    LegacyGameStatsUnknownError = 1501,
    LegacyGameStatsMalformedSneakerNetCode = 1502,
    DestinyAccountAcquisitionFailure = 1600,
    DestinyAccountNotFound = 1601,
    DestinyBuildStatsDatabaseError = 1602,
    DestinyCharacterStatsDatabaseError = 1603,
    DestinyPvPStatsDatabaseError = 1604,
    DestinyPvEStatsDatabaseError = 1605,
    DestinyGrimoireStatsDatabaseError = 1606,
    DestinyStatsParameterMembershipTypeParseError = 1607,
    DestinyStatsParameterMembershipIdParseError = 1608,
    DestinyStatsParameterRangeParseError = 1609,
    DestinyStringItemHashNotFound = 1610,
    DestinyStringSetNotFound = 1611,
    DestinyContentLookupNotFoundForKey = 1612,
    DestinyContentItemNotFound = 1613,
    DestinyContentSectionNotFound = 1614,
    DestinyContentPropertyNotFound = 1615,
    DestinyContentConfigNotFound = 1616,
    DestinyContentPropertyBucketValueNotFound = 1617,
    DestinyUnexpectedError = 1618,
    DestinyInvalidAction = 1619,
    DestinyCharacterNotFound = 1620,
    DestinyInvalidFlag = 1621,
    DestinyInvalidRequest = 1622,
    DestinyItemNotFound = 1623,
    DestinyInvalidCustomizationChoices = 1624,
    DestinyVendorItemNotFound = 1625,
    DestinyInternalError = 1626,
    DestinyVendorNotFound = 1627,
    DestinyRecentActivitiesDatabaseError = 1628,
    DestinyItemBucketNotFound = 1629,
    DestinyInvalidMembershipType = 1630,
    DestinyVersionIncompatibility = 1631,
    DestinyItemAlreadyInInventory = 1632,
    DestinyBucketNotFound = 1633,
    DestinyCharacterNotInTower = 1634,
    DestinyCharacterNotLoggedIn = 1635,
    DestinyDefinitionsNotLoaded = 1636,
    DestinyInventoryFull = 1637,
    DestinyItemFailedLevelCheck = 1638,
    DestinyItemFailedUnlockCheck = 1639,
    DestinyItemUnequippable = 1640,
    DestinyItemUniqueEquipRestricted = 1641,
    DestinyNoRoomInDestination = 1642,
    DestinyServiceFailure = 1643,
    DestinyServiceRetired = 1644,
    DestinyTransferFailed = 1645,
    DestinyTransferNotFoundForSourceBucket = 1646,
    DestinyUnexpectedResultInVendorTransferCheck = 1647,
    DestinyUniquenessViolation = 1648,
    DestinyErrorDeserializationFailure = 1649,
    DestinyValidAccountTicketRequired = 1650,
    DestinyShardRelayClientTimeout = 1651,
    DestinyShardRelayProxyTimeout = 1652,
    DestinyPGCRNotFound = 1653,
    DestinyAccountMustBeOffline = 1654,
    DestinyCanOnlyEquipInGame = 1655,
    DestinyCannotPerformActionOnEquippedItem = 1656,
    DestinyQuestAlreadyCompleted = 1657,
    DestinyQuestAlreadyTracked = 1658,
    DestinyTrackableQuestsFull = 1659,
    DestinyItemNotTransferrable = 1660,
    DestinyVendorPurchaseNotAllowed = 1661,
    DestinyContentVersionMismatch = 1662,
    DestinyItemActionForbidden = 1663,
    DestinyRefundInvalid = 1664,
    DestinyPrivacyRestriction = 1665,
    DestinyActionInsufficientPrivileges = 1666,
    DestinyInvalidClaimException = 1667,
    DestinyLegacyPlatformRestricted = 1668,
    DestinyLegacyPlatformInUse = 1669,
    DestinyLegacyPlatformInaccessible = 1670,
    DestinyCannotPerformActionAtThisLocation = 1671,
    DestinyThrottledByGameServer = 1672,
    DestinyItemNotTransferrableHasSideEffects = 1673,
    DestinyItemLocked = 1674,
    DestinyCannotAffordMaterialRequirements = 1675,
    DestinyFailedPlugInsertionRules = 1676,
    DestinySocketNotFound = 1677,
    DestinySocketActionNotAllowed = 1678,
    DestinySocketAlreadyHasPlug = 1679,
    DestinyPlugItemNotAvailable = 1680,
    DestinyCharacterLoggedInNotAllowed = 1681,
    DestinyPublicAccountNotAccessible = 1682,
    DestinyClaimsItemAlreadyClaimed = 1683,
    DestinyClaimsNoInventorySpace = 1684,
    DestinyClaimsRequiredLevelNotMet = 1685,
    DestinyClaimsInvalidState = 1686,
    DestinyNotEnoughRoomForMultipleRewards = 1687,
    DestinyDirectBabelClientTimeout = 1688,
    FbInvalidRequest = 1800,
    FbRedirectMismatch = 1801,
    FbAccessDenied = 1802,
    FbUnsupportedResponseType = 1803,
    FbInvalidScope = 1804,
    FbUnsupportedGrantType = 1805,
    FbInvalidGrant = 1806,
    InvitationExpired = 1900,
    InvitationUnknownType = 1901,
    InvitationInvalidResponseStatus = 1902,
    InvitationInvalidType = 1903,
    InvitationAlreadyPending = 1904,
    InvitationInsufficientPermission = 1905,
    InvitationInvalidCode = 1906,
    InvitationInvalidTargetState = 1907,
    InvitationCannotBeReactivated = 1908,
    InvitationNoRecipients = 1910,
    InvitationGroupCannotSendToSelf = 1911,
    InvitationTooManyRecipients = 1912,
    InvitationInvalid = 1913,
    InvitationNotFound = 1914,
    TokenInvalid = 2000,
    TokenBadFormat = 2001,
    TokenAlreadyClaimed = 2002,
    TokenAlreadyClaimedSelf = 2003,
    TokenThrottling = 2004,
    TokenUnknownRedemptionFailure = 2005,
    TokenPurchaseClaimFailedAfterTokenClaimed = 2006,
    TokenUserAlreadyOwnsOffer = 2007,
    TokenInvalidOfferKey = 2008,
    TokenEmailNotValidated = 2009,
    TokenProvisioningBadVendorOrOffer = 2010,
    TokenPurchaseHistoryUnknownError = 2011,
    TokenThrottleStateUnknownError = 2012,
    TokenUserAgeNotVerified = 2013,
    TokenExceededOfferMaximum = 2014,
    TokenNoAvailableUnlocks = 2015,
    TokenMarketplaceInvalidPlatform = 2016,
    TokenNoMarketplaceCodesFound = 2017,
    TokenOfferNotAvailableForRedemption = 2018,
    TokenUnlockPartialFailure = 2019,
    TokenMarketplaceInvalidRegion = 2020,
    TokenOfferExpired = 2021,
    RAFExceededMaximumReferrals = 2022,
    RAFDuplicateBond = 2023,
    RAFNoValidVeteranDestinyMembershipsFound = 2024,
    RAFNotAValidVeteranUser = 2025,
    RAFCodeAlreadyClaimedOrNotFound = 2026,
    RAFMismatchedDestinyMembershipType = 2027,
    RAFUnableToAccessPurchaseHistory = 2028,
    RAFUnableToCreateBond = 2029,
    RAFUnableToFindBond = 2030,
    RAFUnableToRemoveBond = 2031,
    RAFCannotBondToSelf = 2032,
    RAFInvalidPlatform = 2033,
    RAFGenerateThrottled = 2034,
    RAFUnableToCreateBondVersionMismatch = 2035,
    RAFUnableToRemoveBondVersionMismatch = 2036,
    RAFRedeemThrottled = 2037,
    NoAvailableDiscountCode = 2038,
    DiscountAlreadyClaimed = 2039,
    DiscountClaimFailure = 2040,
    DiscountConfigurationFailure = 2041,
    DiscountGenerationFailure = 2042,
    DiscountAlreadyExists = 2043,
    TokenRequiresCredentialXuid = 2044,
    TokenRequiresCredentialPsnid = 2045,
    OfferRequired = 2046,
    UnknownEververseHistoryError = 2047,
    MissingEververseHistoryError = 2048,
    BungieRewardEmailStateInvalid = 2049,
    BungieRewardNotYetClaimable = 2050,
    MissingOfferConfig = 2051,
    RAFQuestEntitlementRequiresBnet = 2052,
    RAFQuestEntitlementTransportFailure = 2053,
    RAFQuestEntitlementUnknownFailure = 2054,
    RAFVeteranRewardUnknownFailure = 2055,
    RAFTooEarlyToCancelBond = 2056,
    LoyaltyRewardAlreadyRedeemed = 2057,
    UnclaimedLoyaltyRewardEntryNotFound = 2058,
    PartnerOfferPartialFailure = 2059,
    PartnerOfferAlreadyClaimed = 2060,
    PartnerOfferSkuNotFound = 2061,
    PartnerOfferSkuExpired = 2062,
    PartnerOfferPermissionFailure = 2063,
    PartnerOfferNoDestinyAccount = 2064,
    PartnerOfferApplyDataNotFound = 2065,
    ApiExceededMaxKeys = 2100,
    ApiInvalidOrExpiredKey = 2101,
    ApiKeyMissingFromRequest = 2102,
    ApplicationDisabled = 2103,
    ApplicationExceededMax = 2104,
    ApplicationDisallowedByScope = 2105,
    AuthorizationCodeInvalid = 2106,
    OriginHeaderDoesNotMatchKey = 2107,
    AccessNotPermittedByApplicationScope = 2108,
    ApplicationNameIsTaken = 2109,
    RefreshTokenNotYetValid = 2110,
    AccessTokenHasExpired = 2111,
    ApplicationTokenFormatNotValid = 2112,
    ApplicationNotConfiguredForBungieAuth = 2113,
    ApplicationNotConfiguredForOAuth = 2114,
    OAuthAccessTokenExpired = 2115,
    ApplicationTokenKeyIdDoesNotExist = 2116,
    ProvidedTokenNotValidRefreshToken = 2117,
    RefreshTokenExpired = 2118,
    AuthorizationRecordInvalid = 2119,
    TokenPreviouslyRevoked = 2120,
    TokenInvalidMembership = 2121,
    AuthorizationCodeStale = 2122,
    AuthorizationRecordExpired = 2123,
    AuthorizationRecordRevoked = 2124,
    AuthorizationRecordInactiveApiKey = 2125,
    AuthorizationRecordApiKeyMatching = 2126,
    PartnershipInvalidType = 2200,
    PartnershipValidationError = 2201,
    PartnershipValidationTimeout = 2202,
    PartnershipAccessFailure = 2203,
    PartnershipAccountInvalid = 2204,
    PartnershipGetAccountInfoFailure = 2205,
    PartnershipDisabled = 2206,
    PartnershipAlreadyExists = 2207,
    CommunityStreamingUnavailable = 2300,
    TwitchNotLinked = 2500,
    TwitchAccountNotFound = 2501,
    TwitchCouldNotLoadDestinyInfo = 2502,
    TwitchCouldNotRegisterUser = 2503,
    TwitchCouldNotUnregisterUser = 2504,
    TwitchRequiresRelinking = 2505,
    TwitchNoPlatformChosen = 2506,
    TwitchDropHistoryPermissionFailure = 2507,
    TwitchDropsRepairPartialFailure = 2508,
    TwitchNotAuthorized = 2509,
    TwitchUnknownAuthorizationFailure = 2510,
    TrendingCategoryNotFound = 2600,
    TrendingEntryTypeNotSupported = 2601,
    ReportOffenderNotInPgcr = 2700,
    ReportRequestorNotInPgcr = 2701,
    ReportSubmissionFailed = 2702,
    ReportCannotReportSelf = 2703,
    AwaTypeDisabled = 2800,
    AwaTooManyPendingRequests = 2801,
    AwaTheFeatureRequiresARegisteredDevice = 2802,
    AwaRequestWasUnansweredForTooLong = 2803,
    AwaWriteRequestMissingOrInvalidToken = 2804,
    AwaWriteRequestTokenExpired = 2805,
    AwaWriteRequestTokenUsageLimitReached = 2806,
    SteamWebApiError = 2900,
    SteamWebNullResponseError = 2901,
    SteamAccountRequired = 2902,
    SteamNotAuthorized = 2903,
    ClanFireteamNotFound = 3000,
    ClanFireteamAddNoAlternatesForImmediate = 3001,
    ClanFireteamFull = 3002,
    ClanFireteamAltFull = 3003,
    ClanFireteamBlocked = 3004,
    ClanFireteamPlayerEntryNotFound = 3005,
    ClanFireteamPermissions = 3006,
    ClanFireteamInvalidPlatform = 3007,
    ClanFireteamCannotAdjustSlotCount = 3008,
    ClanFireteamInvalidPlayerPlatform = 3009,
    ClanFireteamNotReadyForInvitesNotEnoughPlayers = 3010,
    ClanFireteamGameInvitesNotSupportForPlatform = 3011,
    ClanFireteamPlatformInvitePreqFailure = 3012,
    ClanFireteamInvalidAuthContext = 3013,
    ClanFireteamInvalidAuthProviderPsn = 3014,
    ClanFireteamPs4SessionFull = 3015,
    ClanFireteamInvalidAuthToken = 3016,
    ClanFireteamScheduledFireteamsDisabled = 3017,
    ClanFireteamNotReadyForInvitesNotScheduledYet = 3018,
    ClanFireteamNotReadyForInvitesClosed = 3019,
    ClanFireteamScheduledFireteamsRequireAdminPermissions = 3020,
    ClanFireteamNonPublicMustHaveClan = 3021,
    ClanFireteamPublicCreationRestriction = 3022,
    ClanFireteamAlreadyJoined = 3023,
    ClanFireteamScheduledFireteamsRange = 3024,
    ClanFireteamPublicCreationRestrictionExtended = 3025,
    ClanFireteamExpired = 3026,
    ClanFireteamInvalidAuthProvider = 3027,
    ClanFireteamInvalidAuthProviderXuid = 3028,
    ClanFireteamThrottle = 3029,
    ClanFireteamTooManyOpenScheduledFireteams = 3030,
    ClanFireteamCannotReopenScheduledFireteams = 3031,
    ClanFireteamJoinNoAccountSpecified = 3032,
    ClanFireteamMinDestiny2ProgressForCreation = 3033,
    ClanFireteamMinDestiny2ProgressForJoin = 3034,
    ClanFireteamSMSOrPurchaseRequiredCreate = 3035,
    ClanFireteamPurchaseRequiredCreate = 3036,
    ClanFireteamSMSOrPurchaseRequiredJoin = 3037,
    ClanFireteamPurchaseRequiredJoin = 3038,
    CrossSaveOverriddenAccountNotFound = 3200,
    CrossSaveTooManyOverriddenPlatforms = 3201,
    CrossSaveNoOverriddenPlatforms = 3202,
    CrossSavePrimaryAccountNotFound = 3203,
    CrossSaveRequestInvalid = 3204,
    CrossSaveBungieAccountValidationFailure = 3206,
    CrossSaveOverriddenPlatformNotAllowed = 3207,
    CrossSaveThresholdExceeded = 3208,
    CrossSaveIncompatibleMembershipType = 3209,
    CrossSaveCouldNotFindLinkedAccountForMembershipType = 3210,
    CrossSaveCouldNotCreateDestinyProfileForMembershipType = 3211,
    CrossSaveErrorCreatingDestinyProfileForMembershipType = 3212,
    CrossSaveCannotOverrideSelf = 3213,
    CrossSaveRecentSilverPurchase = 3214,
    CrossSaveSilverBalanceNegative = 3215,
    CrossSaveAccountNotAuthenticated = 3216,
    ErrorOneAccountAlreadyActive = 3217,
    ErrorOneAccountDestinyRestriction = 3218,
    CrossSaveMustMigrateToSteam = 3219,
    CrossSaveSteamAlreadyPaired = 3220,
    CrossSaveCannotPairJustSteamAndBlizzard = 3221,
    CrossSaveCannotPairSteamAloneBeforeShadowkeep = 3222,
    AuthVerificationNotLinkedToAccount = 3300,
    PCMigrationMissingBlizzard = 3400,
    PCMigrationMissingSteam = 3401,
    PCMigrationInvalidBlizzard = 3402,
    PCMigrationInvalidSteam = 3403,
    PCMigrationUnknownFailure = 3404,
    PCMigrationUnknownException = 3405,
    PCMigrationNotLinked = 3406,
    PCMigrationAccountsAlreadyUsed = 3407,
    PCMigrationStepFailed = 3408,
    PCMigrationInvalidBlizzardCrossSaveState = 3409,
    PCMigrationDestinationBanned = 3410,
    PCMigrationDestinyFailure = 3411,
    PCMigrationSilverTransferFailed = 3412,
    PCMigrationEntitlementTransferFailed = 3413,
    PCMigrationCannotStompClanFounder = 3414,
    UnsupportedBrowser = 3500,
    StadiaAccountRequired = 3600,
    ErrorPhoneValidationTooManyUses = 3702,
    ErrorPhoneValidationNoAssociatedPhone = 3703,
    ErrorPhoneValidationCodeInvalid = 3705,
    ErrorPhoneValidationBanned = 3706,
    ErrorPhoneValidationCodeTooRecentlySent = 3707,
    ErrorPhoneValidationCodeExpired = 3708,
    ErrorPhoneValidationInvalidNumberType = 3709,
    ErrorPhoneValidationCodeTooRecentlyChecked = 3710,
    ApplePushErrorUnknown = 3800,
    ApplePushErrorNull = 3801,
    ApplePushErrorTimeout = 3802,
    ApplePushBadRequest = 3803,
    ApplePushFailedAuth = 3804,
    ApplePushThrottled = 3805,
    ApplePushServiceUnavailable = 3806,
    NotAnImageOrVideo = 3807,
    ErrorBungieFriendsBlockFailed = 3900,
    ErrorBungieFriendsAutoReject = 3901,
    ErrorBungieFriendsNoRequestFound = 3902,
    ErrorBungieFriendsAlreadyFriends = 3903,
    ErrorBungieFriendsUnableToRemoveRequest = 3904,
    ErrorBungieFriendsUnableToRemove = 3905,
    ErrorBungieFriendsIdenticalSourceTarget = 3906,
    ErrorBungieFriendsSelf = 3907,
    ErrorBungieBlockSelf = 3908,
    ErrorBungieFriendsListFull = 3910,
    ErrorBungieBlockListFull = 3911,
    ErrorEgsUnknown = 4000,
    ErrorEgsBadRequest = 4001,
    ErrorEgsNotAuthorized = 4002,
    ErrorEgsForbidden = 4003,
    ErrorEgsAccountNotFound = 4004,
    ErrorEgsWebException = 4005,
    ErrorEgsUnavailable = 4006,
    ErrorEgsJwksMissing = 4007,
    ErrorEgsJwtMalformedHeader = 4008,
    ErrorEgsJwtMalformedPayload = 4009,
}

#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr, PartialEq, Debug, Eq, Copy, Clone, Default)]
#[repr(i32)]
pub enum BungieClassType {
    #[default]
    Unknown = -1,
    Titan = 0,
    Hunter = 1,
    Warlock = 2,
}

#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr, PartialEq, Debug, Eq, Copy, Clone, Default)]
#[repr(i32)]
pub enum BungieMembershipType {
    #[default]
    None = 0,
    Xbox = 1,
    Psn = 2,
    Steam = 3,
    Blizzard = 4,
    Stadia = 5,
    Egs = 6,
    Demon = 10,
    BungieNext = 254,
    All = -1,
}

#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr, PartialEq, Debug, Eq, Copy, Clone, Default)]
#[repr(i32)]
pub enum DestinyActivityModeType {
    #[default]
    None = 0,
    Story = 2,
    Strike = 3,
    Raid = 4,
    AllPvP = 5,
    Patrol = 6,
    AllPvE = 7,
    Reserved9 = 9,
    Control = 10,
    Reserved11 = 11,
    Clash = 12,
    Reserved13 = 13,
    CrimsonDoubles = 15,
    Nightfall = 16,
    HeroicNightfall = 17,
    AllStrikes = 18,
    IronBanner = 19,
    Reserved20 = 20,
    Reserved21 = 21,
    Reserved22 = 22,
    Reserved24 = 24,
    AllMayhem = 25,
    Reserved26 = 26,
    Reserved27 = 27,
    Reserved28 = 28,
    Reserved29 = 29,
    Reserved30 = 30,
    Supremacy = 31,
    PrivateMatchesAll = 32,
    Survival = 37,
    Countdown = 38,
    TrialsOfTheNine = 39,
    Social = 40,
    TrialsCountdown = 41,
    TrialsSurvival = 42,
    IronBannerControl = 43,
    IronBannerClash = 44,
    IronBannerSupremacy = 45,
    ScoredNightfall = 46,
    ScoredHeroicNightfall = 47,
    Rumble = 48,
    AllDoubles = 49,
    Doubles = 50,
    PrivateMatchesClash = 51,
    PrivateMatchesControl = 52,
    PrivateMatchesSupremacy = 53,
    PrivateMatchesCountdown = 54,
    PrivateMatchesSurvival = 55,
    PrivateMatchesMayhem = 56,
    PrivateMatchesRumble = 57,
    HeroicAdventure = 58,
    Showdown = 59,
    Lockdown = 60,
    Scorched = 61,
    ScorchedTeam = 62,
    Gambit = 63,
    AllPvECompetitive = 64,
    Breakthrough = 65,
    BlackArmoryRun = 66,
    Salvage = 67,
    IronBannerSalvage = 68,
    PvPCompetitive = 69,
    PvPQuickplay = 70,
    ClashQuickplay = 71,
    ClashCompetitive = 72,
    ControlQuickplay = 73,
    ControlCompetitive = 74,
    GambitPrime = 75,
    Reckoning = 76,
    Menagerie = 77,
    VexOffensive = 78,
    NightmareHunt = 79,
    Elimination = 80,
    Momentum = 81,
    Dungeon = 82,
    Sundial = 83,
    TrialsOfOsiris = 84,
    Dares = 85,
    Offensive = 86,
    LostSector = 87,
    Rift = 88,
    ZoneControl = 89,
    IronBannerRift = 90,
    IronBannerZoneControl = 91,
    Unknown = i32::MAX,
}

impl DestinyActivityModeType {
    pub fn as_str(self) -> &'static str {
        self.into()
    }
}

impl From<&str> for DestinyActivityModeType {
    fn from(value: &str) -> Self {
        match value {
            "None" => DestinyActivityModeType::None,
            "Story" => DestinyActivityModeType::Story,
            "Strike" => DestinyActivityModeType::Strike,
            "Raid" => DestinyActivityModeType::Raid,
            "AllPvP" => DestinyActivityModeType::AllPvP,
            "Patrol" => DestinyActivityModeType::Patrol,
            "AllPvE" => DestinyActivityModeType::AllPvE,
            "Reserved9" => DestinyActivityModeType::Reserved9,
            "Control" => DestinyActivityModeType::Control,
            "Reserved11" => DestinyActivityModeType::Reserved11,
            "Clash" => DestinyActivityModeType::Clash,
            "Reserved13" => DestinyActivityModeType::Reserved13,
            "CrimsonDoubles" => DestinyActivityModeType::CrimsonDoubles,
            "Nightfall" => DestinyActivityModeType::Nightfall,
            "HeroicNightfall" => DestinyActivityModeType::HeroicNightfall,
            "AllStrikes" => DestinyActivityModeType::AllStrikes,
            "IronBanner" => DestinyActivityModeType::IronBanner,
            "Reserved20" => DestinyActivityModeType::Reserved20,
            "Reserved21" => DestinyActivityModeType::Reserved21,
            "Reserved22" => DestinyActivityModeType::Reserved22,
            "Reserved24" => DestinyActivityModeType::Reserved24,
            "AllMayhem" => DestinyActivityModeType::AllMayhem,
            "Reserved26" => DestinyActivityModeType::Reserved26,
            "Reserved27" => DestinyActivityModeType::Reserved27,
            "Reserved28" => DestinyActivityModeType::Reserved28,
            "Reserved29" => DestinyActivityModeType::Reserved29,
            "Reserved30" => DestinyActivityModeType::Reserved30,
            "Supremacy" => DestinyActivityModeType::Supremacy,
            "PrivateMatchesAll" => DestinyActivityModeType::PrivateMatchesAll,
            "Survival" => DestinyActivityModeType::Survival,
            "Countdown" => DestinyActivityModeType::Countdown,
            "TrialsOfTheNine" => DestinyActivityModeType::TrialsOfTheNine,
            "Social" => DestinyActivityModeType::Social,
            "TrialsCountdown" => DestinyActivityModeType::TrialsCountdown,
            "TrialsSurvival" => DestinyActivityModeType::TrialsSurvival,
            "IronBannerControl" => DestinyActivityModeType::IronBannerControl,
            "IronBannerClash" => DestinyActivityModeType::IronBannerClash,
            "IronBannerSupremacy" => DestinyActivityModeType::IronBannerSupremacy,
            "ScoredNightfall" => DestinyActivityModeType::ScoredNightfall,
            "ScoredHeroicNightfall" => DestinyActivityModeType::ScoredHeroicNightfall,
            "Rumble" => DestinyActivityModeType::Rumble,
            "AllDoubles" => DestinyActivityModeType::AllDoubles,
            "Doubles" => DestinyActivityModeType::Doubles,
            "PrivateMatchesClash" => DestinyActivityModeType::PrivateMatchesClash,
            "PrivateMatchesControl" => DestinyActivityModeType::PrivateMatchesControl,
            "PrivateMatchesSupremacy" => DestinyActivityModeType::PrivateMatchesSupremacy,
            "PrivateMatchesCountdown" => DestinyActivityModeType::PrivateMatchesCountdown,
            "PrivateMatchesSurvival" => DestinyActivityModeType::PrivateMatchesSurvival,
            "PrivateMatchesMayhem" => DestinyActivityModeType::PrivateMatchesMayhem,
            "PrivateMatchesRumble" => DestinyActivityModeType::PrivateMatchesRumble,
            "HeroicAdventure" => DestinyActivityModeType::HeroicAdventure,
            "Showdown" => DestinyActivityModeType::Showdown,
            "Lockdown" => DestinyActivityModeType::Lockdown,
            "Scorched" => DestinyActivityModeType::Scorched,
            "ScorchedTeam" => DestinyActivityModeType::ScorchedTeam,
            "Gambit" => DestinyActivityModeType::Gambit,
            "AllPvECompetitive" => DestinyActivityModeType::AllPvECompetitive,
            "Breakthrough" => DestinyActivityModeType::Breakthrough,
            "BlackArmoryRun" => DestinyActivityModeType::BlackArmoryRun,
            "Salvage" => DestinyActivityModeType::Salvage,
            "IronBannerSalvage" => DestinyActivityModeType::IronBannerSalvage,
            "PvPCompetitive" => DestinyActivityModeType::PvPCompetitive,
            "PvPQuickplay" => DestinyActivityModeType::PvPQuickplay,
            "ClashQuickplay" => DestinyActivityModeType::ClashQuickplay,
            "ClashCompetitive" => DestinyActivityModeType::ClashCompetitive,
            "ControlQuickplay" => DestinyActivityModeType::ControlQuickplay,
            "ControlCompetitive" => DestinyActivityModeType::ControlCompetitive,
            "GambitPrime" => DestinyActivityModeType::GambitPrime,
            "Reckoning" => DestinyActivityModeType::Reckoning,
            "Menagerie" => DestinyActivityModeType::Menagerie,
            "VexOffensive" => DestinyActivityModeType::VexOffensive,
            "NightmareHunt" => DestinyActivityModeType::NightmareHunt,
            "Elimination" => DestinyActivityModeType::Elimination,
            "Momentum" => DestinyActivityModeType::Momentum,
            "Dungeon" => DestinyActivityModeType::Dungeon,
            "Sundial" => DestinyActivityModeType::Sundial,
            "TrialsOfOsiris" => DestinyActivityModeType::TrialsOfOsiris,
            "Dares" => DestinyActivityModeType::Dares,
            "Offensive" => DestinyActivityModeType::Offensive,
            "LostSector" => DestinyActivityModeType::LostSector,
            "Rift" => DestinyActivityModeType::Rift,
            "ZoneControl" => DestinyActivityModeType::ZoneControl,
            "IronBannerRift" => DestinyActivityModeType::IronBannerRift,
            "IronBannerZoneControl" => DestinyActivityModeType::IronBannerZoneControl,
            _ => DestinyActivityModeType::Unknown,
        }
    }
}

impl From<i32> for DestinyActivityModeType {
    fn from(input: i32) -> Self {
        match input {
            0 => DestinyActivityModeType::None,
            2 => DestinyActivityModeType::Story,
            3 => DestinyActivityModeType::Strike,
            4 => DestinyActivityModeType::Raid,
            5 => DestinyActivityModeType::AllPvP,
            6 => DestinyActivityModeType::Patrol,
            7 => DestinyActivityModeType::AllPvE,
            9 => DestinyActivityModeType::Reserved9,
            10 => DestinyActivityModeType::Control,
            11 => DestinyActivityModeType::Reserved11,
            12 => DestinyActivityModeType::Clash,
            13 => DestinyActivityModeType::Reserved13,
            15 => DestinyActivityModeType::CrimsonDoubles,
            16 => DestinyActivityModeType::Nightfall,
            17 => DestinyActivityModeType::HeroicNightfall,
            18 => DestinyActivityModeType::AllStrikes,
            19 => DestinyActivityModeType::IronBanner,
            20 => DestinyActivityModeType::Reserved20,
            21 => DestinyActivityModeType::Reserved21,
            22 => DestinyActivityModeType::Reserved22,
            24 => DestinyActivityModeType::Reserved24,
            25 => DestinyActivityModeType::AllMayhem,
            26 => DestinyActivityModeType::Reserved26,
            27 => DestinyActivityModeType::Reserved27,
            28 => DestinyActivityModeType::Reserved28,
            29 => DestinyActivityModeType::Reserved29,
            30 => DestinyActivityModeType::Reserved30,
            31 => DestinyActivityModeType::Supremacy,
            32 => DestinyActivityModeType::PrivateMatchesAll,
            37 => DestinyActivityModeType::Survival,
            38 => DestinyActivityModeType::Countdown,
            39 => DestinyActivityModeType::TrialsOfTheNine,
            40 => DestinyActivityModeType::Social,
            41 => DestinyActivityModeType::TrialsCountdown,
            42 => DestinyActivityModeType::TrialsSurvival,
            43 => DestinyActivityModeType::IronBannerControl,
            44 => DestinyActivityModeType::IronBannerClash,
            45 => DestinyActivityModeType::IronBannerSupremacy,
            46 => DestinyActivityModeType::ScoredNightfall,
            47 => DestinyActivityModeType::ScoredHeroicNightfall,
            48 => DestinyActivityModeType::Rumble,
            49 => DestinyActivityModeType::AllDoubles,
            50 => DestinyActivityModeType::Doubles,
            51 => DestinyActivityModeType::PrivateMatchesClash,
            52 => DestinyActivityModeType::PrivateMatchesControl,
            53 => DestinyActivityModeType::PrivateMatchesSupremacy,
            54 => DestinyActivityModeType::PrivateMatchesCountdown,
            55 => DestinyActivityModeType::PrivateMatchesSurvival,
            56 => DestinyActivityModeType::PrivateMatchesMayhem,
            57 => DestinyActivityModeType::PrivateMatchesRumble,
            58 => DestinyActivityModeType::HeroicAdventure,
            59 => DestinyActivityModeType::Showdown,
            60 => DestinyActivityModeType::Lockdown,
            61 => DestinyActivityModeType::Scorched,
            62 => DestinyActivityModeType::ScorchedTeam,
            63 => DestinyActivityModeType::Gambit,
            64 => DestinyActivityModeType::AllPvECompetitive,
            65 => DestinyActivityModeType::Breakthrough,
            66 => DestinyActivityModeType::BlackArmoryRun,
            67 => DestinyActivityModeType::Salvage,
            68 => DestinyActivityModeType::IronBannerSalvage,
            69 => DestinyActivityModeType::PvPCompetitive,
            70 => DestinyActivityModeType::PvPQuickplay,
            71 => DestinyActivityModeType::ClashQuickplay,
            72 => DestinyActivityModeType::ClashCompetitive,
            73 => DestinyActivityModeType::ControlQuickplay,
            74 => DestinyActivityModeType::ControlCompetitive,
            75 => DestinyActivityModeType::GambitPrime,
            76 => DestinyActivityModeType::Reckoning,
            77 => DestinyActivityModeType::Menagerie,
            78 => DestinyActivityModeType::VexOffensive,
            79 => DestinyActivityModeType::NightmareHunt,
            80 => DestinyActivityModeType::Elimination,
            81 => DestinyActivityModeType::Momentum,
            82 => DestinyActivityModeType::Dungeon,
            83 => DestinyActivityModeType::Sundial,
            84 => DestinyActivityModeType::TrialsOfOsiris,
            85 => DestinyActivityModeType::Dares,
            86 => DestinyActivityModeType::Offensive,
            87 => DestinyActivityModeType::LostSector,
            88 => DestinyActivityModeType::Rift,
            89 => DestinyActivityModeType::ZoneControl,
            90 => DestinyActivityModeType::IronBannerRift,
            91 => DestinyActivityModeType::IronBannerZoneControl,
            _ => DestinyActivityModeType::Unknown,
        }
    }
}

impl From<DestinyActivityModeType> for &'static str {
    fn from(value: DestinyActivityModeType) -> Self {
        match value {
            DestinyActivityModeType::None => "None",
            DestinyActivityModeType::Story => "Story",
            DestinyActivityModeType::Strike => "Strike",
            DestinyActivityModeType::Raid => "Raid",
            DestinyActivityModeType::AllPvP => "AllPvP",
            DestinyActivityModeType::Patrol => "Patrol",
            DestinyActivityModeType::AllPvE => "AllPvE",
            DestinyActivityModeType::Reserved9 => "Reserved9",
            DestinyActivityModeType::Control => "Control",
            DestinyActivityModeType::Reserved11 => "Reserved11",
            DestinyActivityModeType::Clash => "Clash",
            DestinyActivityModeType::Reserved13 => "Reserved13",
            DestinyActivityModeType::CrimsonDoubles => "CrimsonDoubles",
            DestinyActivityModeType::Nightfall => "Nightfall",
            DestinyActivityModeType::HeroicNightfall => "HeroicNightfall",
            DestinyActivityModeType::AllStrikes => "AllStrikes",
            DestinyActivityModeType::IronBanner => "IronBanner",
            DestinyActivityModeType::Reserved20 => "Reserved20",
            DestinyActivityModeType::Reserved21 => "Reserved21",
            DestinyActivityModeType::Reserved22 => "Reserved22",
            DestinyActivityModeType::Reserved24 => "Reserved24",
            DestinyActivityModeType::AllMayhem => "AllMayhem",
            DestinyActivityModeType::Reserved26 => "Reserved26",
            DestinyActivityModeType::Reserved27 => "Reserved27",
            DestinyActivityModeType::Reserved28 => "Reserved28",
            DestinyActivityModeType::Reserved29 => "Reserved29",
            DestinyActivityModeType::Reserved30 => "Reserved30",
            DestinyActivityModeType::Supremacy => "Supremacy",
            DestinyActivityModeType::PrivateMatchesAll => "PrivateMatchesAll",
            DestinyActivityModeType::Survival => "Survival",
            DestinyActivityModeType::Countdown => "Countdown",
            DestinyActivityModeType::TrialsOfTheNine => "TrialsOfTheNine",
            DestinyActivityModeType::Social => "Social",
            DestinyActivityModeType::TrialsCountdown => "TrialsCountdown",
            DestinyActivityModeType::TrialsSurvival => "TrialsSurvival",
            DestinyActivityModeType::IronBannerControl => "IronBannerControl",
            DestinyActivityModeType::IronBannerClash => "IronBannerClash",
            DestinyActivityModeType::IronBannerSupremacy => "IronBannerSupremacy",
            DestinyActivityModeType::ScoredNightfall => "ScoredNightfall",
            DestinyActivityModeType::ScoredHeroicNightfall => "ScoredHeroicNightfall",
            DestinyActivityModeType::Rumble => "Rumble",
            DestinyActivityModeType::AllDoubles => "AllDoubles",
            DestinyActivityModeType::Doubles => "Doubles",
            DestinyActivityModeType::PrivateMatchesClash => "PrivateMatchesClash",
            DestinyActivityModeType::PrivateMatchesControl => "PrivateMatchesControl",
            DestinyActivityModeType::PrivateMatchesSupremacy => "PrivateMatchesSupremacy",
            DestinyActivityModeType::PrivateMatchesCountdown => "PrivateMatchesCountdown",
            DestinyActivityModeType::PrivateMatchesSurvival => "PrivateMatchesSurvival",
            DestinyActivityModeType::PrivateMatchesMayhem => "PrivateMatchesMayhem",
            DestinyActivityModeType::PrivateMatchesRumble => "PrivateMatchesRumble",
            DestinyActivityModeType::HeroicAdventure => "HeroicAdventure",
            DestinyActivityModeType::Showdown => "Showdown",
            DestinyActivityModeType::Lockdown => "Lockdown",
            DestinyActivityModeType::Scorched => "Scorched",
            DestinyActivityModeType::ScorchedTeam => "ScorchedTeam",
            DestinyActivityModeType::Gambit => "Gambit",
            DestinyActivityModeType::AllPvECompetitive => "AllPvECompetitive",
            DestinyActivityModeType::Breakthrough => "Breakthrough",
            DestinyActivityModeType::BlackArmoryRun => "BlackArmoryRun",
            DestinyActivityModeType::Salvage => "Salvage",
            DestinyActivityModeType::IronBannerSalvage => "IronBannerSalvage",
            DestinyActivityModeType::PvPCompetitive => "PvPCompetitive",
            DestinyActivityModeType::PvPQuickplay => "PvPQuickplay",
            DestinyActivityModeType::ClashQuickplay => "ClashQuickplay",
            DestinyActivityModeType::ClashCompetitive => "ClashCompetitive",
            DestinyActivityModeType::ControlQuickplay => "ControlQuickplay",
            DestinyActivityModeType::ControlCompetitive => "ControlCompetitive",
            DestinyActivityModeType::GambitPrime => "GambitPrime",
            DestinyActivityModeType::Reckoning => "Reckoning",
            DestinyActivityModeType::Menagerie => "Menagerie",
            DestinyActivityModeType::VexOffensive => "VexOffensive",
            DestinyActivityModeType::NightmareHunt => "NightmareHunt",
            DestinyActivityModeType::Elimination => "Elimination",
            DestinyActivityModeType::Momentum => "Momentum",
            DestinyActivityModeType::Dungeon => "Dungeon",
            DestinyActivityModeType::Sundial => "Sundial",
            DestinyActivityModeType::TrialsOfOsiris => "TrialsOfOsiris",
            DestinyActivityModeType::Dares => "Dares",
            DestinyActivityModeType::Offensive => "Offensive",
            DestinyActivityModeType::LostSector => "LostSector",
            DestinyActivityModeType::Rift => "Rift",
            DestinyActivityModeType::ZoneControl => "ZoneControl",
            DestinyActivityModeType::IronBannerRift => "IronBannerRift",
            DestinyActivityModeType::IronBannerZoneControl => "IronBannerZoneControl",
            DestinyActivityModeType::Unknown => "Unknown",
        }
    }
}
