// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ClanInformation { group_id: bigint, name: string, call_sign: string, is_network: boolean, member_count?: number, slug?: string, motto?: string, about?: string, }