// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberResponse } from "./MemberResponse";

export interface ClanResponse { group_id: string, name: string, call_sign: string, is_network: boolean, member_count?: number, slug?: string, motto?: string, about?: string, roster: Array<MemberResponse>, }