// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LeaderboardEntry { display_name: string, amount: number, standing: number, percent_ranking: number, percent_distance: number, }