// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeaderboardEntry } from "./LeaderboardEntry";

export interface Leaderboard { name: string, entries: Array<LeaderboardEntry>, description: string, }