// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberClanInformation } from "./MemberClanInformation";

export interface MemberResponse { display_name: string, display_name_platform: string, membership_id: string, membership_platform: number, timestamp_last_played: number, raid_report: string, clan?: MemberClanInformation, }