// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MemberReportStats { kills: number, deaths: number, assists: number, victories: number, defeats: number, activities: number, activity_completions: number, activities_completed_start_to_finish: number, }