// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MemberTitle { title: string, gilded_past: boolean, gilded_amount: number, gilded_season: boolean, }