// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MemberReportActivity { attempts: number, completions: number, name: string, description: string, }