// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NetworkActivityClanBreakdown { group_id: string, name: string, total_members: number, activity_attempts: number, activities_completed_with_clan: number, activities_completed: number, percent_with_clan: number, avg_clan_member_amount: number, }