// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberReport } from "./MemberReport";

export type ReportOutput = bigint | MemberReport;