// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SettingModeRecord { id: bigint, leaderboard: bigint, dashboard: bigint, name: string, value: string, description: string, order: bigint, created_at: bigint, updated_at: bigint, deleted_at: bigint, }