// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AccountLinkedPlatformsResult { account_token: string, username: string, discord: string, bungie: string, twitch: string, }